name: hello-git-actions
on: [push]
jobs:
  # macos-build:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       id: cache
  #       with:
  #         path: /Users/runner/.cache/vcpkg
  #         key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
  #     - name: Configure
  #       run: bash .github/scripts/configure.sh
  #     - name: Build
  #       run: bash .github/scripts/build.sh
  # windows-build:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Configure
  #       run: .github/scripts/configure.bat
  #     - name: Build
  #       run: .github/scripts/build.bat
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.cache/vcpkg
          key: vcpkg-archives-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Configure
        run: bash .github/scripts/configure-linux.sh
      - name: Build
        run: bash .github/scripts/build.sh

  deploy:
    runs-on: ubuntu-latest
    needs: [linux-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Butler
        run: |
          bash ./.github/scripts/install-butler.sh
