name: hello-git-actions
on: [push]
jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -B build
      - name: Build
        run: bash .github/scripts/build.sh
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -B build
      - name: Build
        run: .github/scripts/build.bat
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -B build
      - name: Build
        run: bash .github/scripts/build.sh

  deploy:
    runs-on: ubuntu-latest
    needs: [linux-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Butler
        run: |
          bash ./.github/scripts/install-butler.sh
